import '../domain/ai_execution_plan.dart';

/// Validates AI execution plans generated by LLM models before execution.
class AiPlanValidator {
  const AiPlanValidator();

  static const maxAllowedSteps = 4;
  static const supportedTools = <String>{
    'search_clipboard',
    'extract_urls',
    'explain_content',
    'summarize_text',
    'translate_text',
    'rewrite_content',
    'classify_type',
    'refine_ocr',
    'qa_clipboard',
  };

  /// Validates [plan] and returns true if it meets all safety and execution criteria.
  bool isValid(AiExecutionPlan plan) {
    if (plan.steps.isEmpty || plan.steps.length > maxAllowedSteps) {
      return false;
    }

    final validStepIds = <int>{};

    for (var index = 0; index < plan.steps.length; index++) {
      final step = plan.steps[index];

      // Check tool whitelist
      if (!supportedTools.contains(step.tool)) {
        return false;
      }

      // Check dependency references (e.g. $step_1 must reference an earlier step)
      for (final value in step.arguments.values) {
        if (value is String && value.startsWith(r'$step_')) {
          final refNumStr = value.replaceFirst(r'$step_', '');
          final refNum = int.tryParse(refNumStr);
          if (refNum == null || !validStepIds.contains(refNum)) {
            return false;
          }
        }
      }

      validStepIds.add(step.stepId);
    }

    return true;
  }

  /// Validates [plan]. If invalid, returns a safe single-step fallback plan.
  AiExecutionPlan validateOrFallback(
    AiExecutionPlan? plan, {
    required String defaultTool,
    required String defaultLanguage,
    Map<String, dynamic> defaultArguments = const {},
  }) {
    if (plan != null && isValid(plan)) {
      return plan;
    }
    return AiExecutionPlan.singleStepFallback(
      tool: defaultTool,
      language: defaultLanguage,
      arguments: defaultArguments,
    );
  }
}
